## 制作第一个BaseLine
算法的研发：迭代的过程

BaseLine -> V0.1.0 -> V0.2.0...

数据读入 -> 数据处理 -> 训练集/评测集制作 -> 机器学习 -> 模型评测( -> 模型集成 -> 应用开发)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
train = pd.read_csv('data/train.csv') #训练集的获取

In [3]:
train.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [4]:
train.get_dtype_counts()

float64     3
int64      35
object     43
dtype: int64

In [5]:
train1 = train # 拷贝数据

----

## 数据的简单填充

### Numerical
1. 均值填充
2. 中位数
3. 函数填充（需要和数据集中某些列产生函数映射关系）

In [6]:
empty = train.isnull().sum()
empty = empty[empty > 0]
empty.shape

(19,)

In [7]:
#均值填充
train1 = train1.fillna(train1.mean()) # 填充平均值

### Categorial填充
1. 控制填充【增加一个"None"-"NA"】

2. 高频填充

3. 关系填充【根据数据的含义，参考其他的列进行填充】

In [8]:
train1 = train1.fillna("None")

In [9]:
def getNullCount(t):
    enpty = t.isnull().sum()
    print(enpty[enpty > 0])

In [10]:
getNullCount(train1)

Series([], dtype: int64)

至此，已经完成了暴力填充

-----

## 训练集的制作

In [11]:
y = train1['SalePrice']
train1 = train1.drop(['Id' ,'SalePrice'], axis = 1)

In [12]:
train1.head(10)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.000000,8450,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,None,None,0,2,2008,WD,Normal
1,20,RL,80.000000,9600,Pave,None,Reg,Lvl,AllPub,FR2,...,0,0,None,None,None,0,5,2007,WD,Normal
2,60,RL,68.000000,11250,Pave,None,IR1,Lvl,AllPub,Inside,...,0,0,None,None,None,0,9,2008,WD,Normal
3,70,RL,60.000000,9550,Pave,None,IR1,Lvl,AllPub,Corner,...,0,0,None,None,None,0,2,2006,WD,Abnorml
4,60,RL,84.000000,14260,Pave,None,IR1,Lvl,AllPub,FR2,...,0,0,None,None,None,0,12,2008,WD,Normal
5,50,RL,85.000000,14115,Pave,None,IR1,Lvl,AllPub,Inside,...,0,0,None,MnPrv,Shed,700,10,2009,WD,Normal
6,20,RL,75.000000,10084,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,None,None,0,8,2007,WD,Normal
7,60,RL,70.049958,10382,Pave,None,IR1,Lvl,AllPub,Corner,...,0,0,None,None,Shed,350,11,2009,WD,Normal
8,50,RM,51.000000,6120,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,None,None,0,4,2008,WD,Abnorml
9,190,RL,50.000000,7420,Pave,None,Reg,Lvl,AllPub,Corner,...,0,0,None,None,None,0,1,2008,WD,Normal

In [13]:
x = pd.get_dummies(train1).reset_index(drop = True) # one_hot

In [14]:
x.head(10)

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.000000,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.000000,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.000000,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.000000,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.000000,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0
5,50,85.000000,14115,5,5,1993,1995,0.0,732,0,...,0,0,0,1,0,0,0,0,1,0
6,20,75.000000,10084,8,5,2004,2005,186.0,1369,0,...,0,0,0,1,0,0,0,0,1,0
7,60,70.049958,10382,7,6,1973,1973,240.0,859,32,...,0,0,0,1,0,0,0,0,1,0
8,50,51.000000,6120,7,5,1931,1950,0.0,0,0,...,0,0,0,1,1,0,0,0,0,0
9,190,50.000000,7420,5,6,1939,1950,0.0,851,0,...,0,0,0,1,0,0,0,0,1,0

In [15]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import numpy as np

In [16]:
matrix = xgb.DMatrix(data = x,label = y)

In [17]:
# 数据集进行拆分，80%训练，20%用来测试
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 123)

In [18]:
x_train.shape

(1168, 303)

In [19]:
x_test.shape

(292, 303)

In [20]:
# XGBoost
xg_reg = xgb.XGBRegressor(objective = 'reg:linear',colsample_bytree = 0.6,learning_rate = 0.01,max_depth = 8,alpha = 10, n_estimators = 700, subsample = 0.7)

In [21]:
xg_reg.fit(x_train,y_train)

XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.6, gamma=0, learning_rate=0.01, max_delta_step=0,
       max_depth=8, min_child_weight=1, missing=None, n_estimators=700,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.7)

In [22]:
pred = xg_reg.predict(x_test)

In [23]:
pred

array([229148.11 , 109361.195, 142593.22 , 247349.4  , 141027.81 ,
       238403.16 , 308208.97 , 128436.94 , 138085.08 , 116737.914,
       150881.2  , 226668.62 , 146242.81 , 117486.914, 248223.61 ,
       184838.88 , 149018.81 , 372203.1  , 226771.38 , 172892.62 ,
       149657.8  , 182033.45 , 110389.64 , 144045.69 , 219347.95 ,
       142290.08 , 212687.97 , 188664.73 , 124740.89 , 138588.28 ,
       136226.81 , 218393.94 , 143621.19 , 204444.58 , 361878.66 ,
       200971.28 , 165720.98 , 322275.28 , 175296.92 ,  94419.5  ,
       134395.12 , 207749.73 , 190664.55 , 165186.31 , 212171.02 ,
       117582.27 , 277346.22 , 219969.2  , 243411.47 , 116925.19 ,
       205129.47 , 181594.34 , 149271.89 , 157501.66 , 108285.555,
       159136.42 , 131748.72 , 168680.19 , 233667.55 , 381274.84 ,
       108261.664, 364476.12 , 147203.77 , 169949.95 , 213989.95 ,
       140671.56 , 116138.734, 221808.83 , 244587.64 , 142338.88 ,
       150785.55 , 206446.48 , 160517.64 , 251029.9  , 146502.38 ,
       122136.27 , 182783.66 , 134853.84 , 216061.2  , 147100.73 ,
       323172.66 , 282095.34 ,  88650.33 , 127070.41 , 171942.98 ,
       138053.5  ,  92335.734, 116053.5  ,  71948.19 , 289837.4  ,
       125573.04 , 173292.7  , 174671.22 , 165835.06 , 143987.14 ,
       124261.55 , 227311.61 , 103939.516, 232519.78 , 131638.72 ,
       121832.04 , 412726.72 , 346879.16 , 154965.27 , 194324.1  ,
       131261.53 , 127659.66 , 212784.23 , 175512.55 , 308208.22 ,
       286580.28 , 240650.55 , 111976.56 , 263927.88 , 177540.16 ,
       123448.54 , 173752.27 , 379752.56 , 108364.086, 148379.36 ,
       171565.83 , 205948.05 , 200758.73 , 123430.19 , 259190.78 ,
       264456.88 , 116500.64 , 119176.984, 161792.86 , 288466.   ,
        97101.73 , 316558.47 , 264049.97 , 186045.55 , 224328.75 ,
       167416.92 , 336717.06 , 111792.33 , 185000.69 , 127899.44 ,
       111217.125, 223645.84 , 241053.94 , 146341.45 , 202201.77 ,
       252473.69 , 216258.06 , 175857.89 , 179733.83 , 123334.79 ,
       192366.6  , 119245.445, 421076.97 , 172379.1  , 293077.16 ,
       157381.81 , 245571.94 , 134986.19 , 132163.52 , 138863.36 ,
       503965.3  , 219492.08 , 236021.55 , 141101.27 , 234408.73 ,
       102169.055, 148922.3  , 133080.83 , 176121.27 , 115257.56 ,
       127294.28 , 133207.03 , 228534.34 , 229318.1  , 136452.56 ,
       290600.72 , 173494.02 , 118730.74 , 196753.89 , 220802.58 ,
       183012.5  , 144455.7  , 132308.9  , 142221.69 , 164820.64 ,
       127006.83 , 126135.805, 189665.7  , 173962.38 , 174625.73 ,
       130579.484, 136571.4  , 194619.7  , 241049.38 , 124729.71 ,
       267477.9  , 135933.14 , 112721.98 , 168958.66 , 112838.32 ,
       189235.75 , 343680.   , 171262.77 , 360396.75 , 172855.42 ,
       131514.9  , 110806.85 , 304804.12 , 150959.55 , 221741.6  ,
       158656.78 , 379359.25 , 126547.73 , 150211.33 , 151194.25 ,
       212336.94 , 203216.45 , 135823.38 , 123492.516, 105026.31 ,
       179338.86 ,  84511.56 , 139028.8  , 120285.44 , 113125.29 ,
       111692.31 , 179584.23 ,  93767.79 , 146322.39 , 125350.22 ,
       113912.75 , 143657.   , 167172.81 , 124696.64 , 121187.7  ,
       167188.44 , 203048.84 , 123004.65 , 180570.48 , 101201.37 ,
       257451.67 , 260830.53 , 202580.69 , 207051.12 , 123098.98 ,
       252753.48 , 122165.59 , 293850.8  , 116519.82 , 255765.45 ,
       217570.86 , 112210.68 , 207866.92 , 105505.95 , 168669.22 ,
       204844.98 , 267660.84 , 207938.05 , 143939.22 , 108444.81 ,
       208675.38 , 201319.42 , 170854.77 , 193316.1  , 172869.84 ,
       144661.08 , 159911.42 , 201960.64 ,  73825.6  , 111645.875,
       134427.03 ,  85520.25 , 206264.84 ,  97867.67 , 268700.66 ,
       176970.47 , 188970.8  , 229789.33 , 141535.47 , 115995.84 ,
       133457.9  , 145338.95 , 107548.93 , 133027.34 , 174354.34 ,
       123547.555, 171790.16 , 153499.86 , 188667.8  , 118062.3  ,
       191236.17 ,  91053.05 ], dtype=float32)

In [24]:
rmse = np.sqrt(mean_squared_error(np.log(y_test),np.log(pred)))

In [25]:
rmse

0.11525108103109791