## 制作第一个BaseLine
算法的研发：迭代的过程

BaseLine -> V0.1.0 -> V0.2.0...

数据读入 -> 数据处理 -> 训练集/评测集制作 -> 机器学习 -> 模型评测( -> 模型集成 -> 应用开发)

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
train = pd.read_csv('data/train.csv') #训练集的获取

In [9]:
train.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [10]:
train.get_dtype_counts()

float64     3
int64      35
object     43
dtype: int64

In [11]:
train1 = train # 拷贝数据

----

## 数据的简单填充

### Numerical
1. 均值填充
2. 中位数
3. 函数填充（需要和数据集中某些列产生函数映射关系）

In [12]:
empty = train.isnull().sum()
empty = empty[empty > 0]
empty.shape

(19,)

In [13]:
#均值填充
train1 = train1.fillna(train1.mean()) # 填充平均值

### Categorial填充
1. 控制填充【增加一个"None"-"NA"】

2. 高频填充

3. 关系填充【根据数据的含义，参考其他的列进行填充】

In [14]:
train1 = train1.fillna("None")

In [15]:
def getNullCount(t):
    enpty = t.isnull().sum()
    print(enpty[enpty > 0])

In [16]:
getNullCount(train1)

Series([], dtype: int64)

至此，已经完成了暴力填充

-----

## 训练集的制作

In [17]:
y = train1['SalePrice']
train1 = train1.drop(['Id' ,'SalePrice'], axis = 1)

In [18]:
train1.head(10)

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.000000,8450,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,None,None,0,2,2008,WD,Normal
1,20,RL,80.000000,9600,Pave,None,Reg,Lvl,AllPub,FR2,...,0,0,None,None,None,0,5,2007,WD,Normal
2,60,RL,68.000000,11250,Pave,None,IR1,Lvl,AllPub,Inside,...,0,0,None,None,None,0,9,2008,WD,Normal
3,70,RL,60.000000,9550,Pave,None,IR1,Lvl,AllPub,Corner,...,0,0,None,None,None,0,2,2006,WD,Abnorml
4,60,RL,84.000000,14260,Pave,None,IR1,Lvl,AllPub,FR2,...,0,0,None,None,None,0,12,2008,WD,Normal
5,50,RL,85.000000,14115,Pave,None,IR1,Lvl,AllPub,Inside,...,0,0,None,MnPrv,Shed,700,10,2009,WD,Normal
6,20,RL,75.000000,10084,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,None,None,0,8,2007,WD,Normal
7,60,RL,70.049958,10382,Pave,None,IR1,Lvl,AllPub,Corner,...,0,0,None,None,Shed,350,11,2009,WD,Normal
8,50,RM,51.000000,6120,Pave,None,Reg,Lvl,AllPub,Inside,...,0,0,None,None,None,0,4,2008,WD,Abnorml
9,190,RL,50.000000,7420,Pave,None,Reg,Lvl,AllPub,Corner,...,0,0,None,None,None,0,1,2008,WD,Normal

In [19]:
x = pd.get_dummies(train1).reset_index(drop = True) # one_hot

In [20]:
x.head(10)

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,65.000000,8450,7,5,2003,2003,196.0,706,0,...,0,0,0,1,0,0,0,0,1,0
1,20,80.000000,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,1,0,0,0,0,1,0
2,60,68.000000,11250,7,5,2001,2002,162.0,486,0,...,0,0,0,1,0,0,0,0,1,0
3,70,60.000000,9550,7,5,1915,1970,0.0,216,0,...,0,0,0,1,1,0,0,0,0,0
4,60,84.000000,14260,8,5,2000,2000,350.0,655,0,...,0,0,0,1,0,0,0,0,1,0
5,50,85.000000,14115,5,5,1993,1995,0.0,732,0,...,0,0,0,1,0,0,0,0,1,0
6,20,75.000000,10084,8,5,2004,2005,186.0,1369,0,...,0,0,0,1,0,0,0,0,1,0
7,60,70.049958,10382,7,6,1973,1973,240.0,859,32,...,0,0,0,1,0,0,0,0,1,0
8,50,51.000000,6120,7,5,1931,1950,0.0,0,0,...,0,0,0,1,1,0,0,0,0,0
9,190,50.000000,7420,5,6,1939,1950,0.0,851,0,...,0,0,0,1,0,0,0,0,1,0

In [24]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split
import numpy as np

In [25]:
matrix = xgb.DMatrix(data = x,label = y)

In [26]:
# 数据集进行拆分，80%训练，20%用来测试
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 123)

In [27]:
x_train.shape

(1168, 303)

In [28]:
x_test.shape

(292, 303)

In [30]:
# XGBoost
xg_reg = xgb.XGBRegressor(objective = 'reg:linear',colsample_bytree = 0.4,learning_rate = 0.01,max_depth = 8,alpha = 10, n_estimators = 200, subsample = 0.7)

In [32]:
xg_reg.fit(x_train,y_train)

XGBRegressor(alpha=10, base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=0.4, gamma=0, learning_rate=0.01, max_delta_step=0,
       max_depth=8, min_child_weight=1, missing=None, n_estimators=200,
       n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=0.7)

In [33]:
pred = xg_reg.predict(x_test)

In [34]:
pred

array([197395.28 , 105024.83 , 126992.37 , 202250.06 , 122510.055,
       213211.22 , 264926.72 , 110276.54 , 124213.89 , 100890.125,
       127221.92 , 199451.55 , 124895.59 , 107858.51 , 209615.4  ,
       147672.44 , 126038.625, 310938.16 , 191940.55 , 142576.75 ,
       125935.13 , 159236.25 ,  97821.64 , 125297.23 , 189948.67 ,
       126828.055, 185043.67 , 161429.75 , 111281.984, 120911.16 ,
       121125.73 , 176088.28 , 124599.41 , 173591.7  , 290502.25 ,
       180720.47 , 146649.81 , 255862.44 , 145063.94 ,  82395.664,
       116767.96 , 184961.55 , 150452.3  , 144773.45 , 184959.33 ,
       101086.37 , 240931.1  , 186658.98 , 211036.38 , 102818.01 ,
       166529.88 , 164270.44 , 126047.58 , 139964.11 ,  91941.63 ,
       135620.78 , 110186.93 , 140844.72 , 201157.73 , 323865.2  ,
        95598.13 , 293418.9  , 125165.875, 145226.84 , 186612.94 ,
       117351.766, 101663.87 , 195942.97 , 207679.5  , 124277.12 ,
       129042.414, 170284.06 , 140487.45 , 224926.12 , 128054.   ,
       110664.74 , 158842.86 , 119941.48 , 187642.39 , 123483.22 ,
       281758.34 , 245255.9  ,  82677.13 , 110682.37 , 139745.05 ,
       119202.25 ,  83055.65 , 103850.62 ,  61222.523, 212047.61 ,
       109573.65 , 156963.5  , 154855.42 , 141233.05 , 126984.945,
       111230.26 , 182536.23 ,  93898.66 , 199708.17 , 114742.32 ,
       105887.02 , 325352.34 , 267287.7  , 135144.62 , 167866.98 ,
       117644.65 , 108731.02 , 180621.34 , 147524.17 , 260280.55 ,
       241049.47 , 187461.12 ,  95494.55 , 225205.38 , 155985.39 ,
       103772.055, 152131.8  , 323880.06 ,  94028.03 , 129982.266,
       139809.19 , 178220.53 , 171375.94 , 105769.875, 226723.92 ,
       228152.25 ,  98495.65 , 109055.69 , 132440.78 , 247009.86 ,
        90335.78 , 263815.7  , 223614.8  , 160609.   , 178395.31 ,
       138942.25 , 286236.12 ,  97682.586, 155859.25 , 111867.3  ,
        97310.15 , 183761.62 , 200019.06 , 124905.69 , 170455.39 ,
       198166.11 , 201005.78 , 143406.06 , 155945.3  , 111765.8  ,
       161793.78 , 110055.14 , 340743.   , 149417.19 , 258595.42 ,
       135996.9  , 214755.5  , 118975.805, 117086.5  , 118833.375,
       388629.6  , 184776.53 , 195144.28 , 122614.39 , 207840.66 ,
        90887.35 , 128158.53 , 113454.91 , 157231.67 , 105048.52 ,
       112265.05 , 112541.61 , 185799.53 , 193178.92 , 120371.03 ,
       248229.1  , 155671.58 , 105027.85 , 168652.2  , 200300.9  ,
       153519.08 , 120045.19 , 112943.8  , 122989.34 , 141804.42 ,
       108415.17 , 114844.11 , 164392.02 , 142633.81 , 151649.44 ,
       116242.5  , 119371.48 , 171422.22 , 210113.86 , 107096.44 ,
       236371.25 , 112511.67 ,  97049.4  , 140045.73 , 102636.23 ,
       166169.89 , 286230.8  , 151297.06 , 294098.53 , 150919.02 ,
       115857.61 ,  97090.33 , 243623.34 , 133162.98 , 189532.27 ,
       134103.39 , 335573.   , 113549.86 , 131736.58 , 127544.625,
       178842.94 , 178374.14 , 111162.6  , 109524.37 ,  92409.3  ,
       162088.56 ,  79231.414, 124862.125, 105262.75 ,  95947.45 ,
       104271.85 , 156420.16 ,  88653.56 , 130971.76 , 111378.26 ,
       108402.88 , 126873.414, 147598.03 , 109998.05 , 108859.055,
       147556.08 , 162202.38 , 108937.75 , 161936.92 ,  92604.59 ,
       222618.42 , 221550.97 , 180040.42 , 185439.7  , 109726.37 ,
       223489.33 , 111801.96 , 250057.3  , 109682.53 , 223109.06 ,
       197361.02 ,  95575.66 , 179359.92 ,  93595.4  , 152238.17 ,
       180485.48 , 235981.48 , 177210.12 , 123720.4  ,  90193.6  ,
       181020.95 , 172694.55 , 142359.5  , 166644.17 , 154520.33 ,
       126450.56 , 143206.22 , 170167.55 ,  69888.95 , 101777.3  ,
       115887.58 ,  75692.66 , 185761.84 ,  88267.21 , 227410.25 ,
       145914.78 , 170450.73 , 201942.33 , 117044.375, 102065.69 ,
       117642.8  , 124816.41 ,  98003.64 , 117254.34 , 146377.25 ,
       112235.805, 154180.55 , 123272.86 , 156287.12 , 108556.41 ,
       161488.12 ,  81539.   ], dtype=float32)

In [42]:
rmse = np.sqrt(mean_squared_error(np.log(y_test),np.log(pred)))

In [43]:
rmse

0.18986113375428385